ImportError: cannot import name 'home_page' from 'pages.home' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\home.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 33, in <module>
    from pages.home import home_page



Traceback (most recent call last):
  File "d:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 2, in <module>      
    from utils.auth import register_user, login_user
ImportError: cannot import name 'register_user' from 'utils.auth' (d:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\utils\auth.py)



ImportError: cannot import name 'dashboard_page' from 'pages.dashboard' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\dashboard.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 36, in <module>
    from pages.dashboard import dashboard_page



ImportError: cannot import name 'calculator_page' from 'pages.calculator' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\calculator.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 42, in <module>
    from pages.calculator import calculator_page




ImportError: cannot import name 'compare_page' from 'pages.compare' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\compare.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 39, in <module>
    from pages.compare import compare_page




ImportError: cannot import name 'currency_exchange_page' from 'pages.currency_exchanger' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\currency_exchanger.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 45, in <module>
    from pages.currency_exchanger import currency_exchange_page



ImportError: cannot import name 'ai_chatbox' from 'pages.ai_chatbox' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\ai_chatbox.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 48, in <module>
    from pages.ai_chatbox import ai_chatbox


No data available for one or both of the selected stocks. Please try again later. (in compare_page)


AttributeError: module 'pages.calculator' has no attribute 'profit_loss_calculator'
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 43, in <module>
    calculator.profit_loss_calculator()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


ImportError: cannot import name 'calculator_page' from 'pages.calculator' (D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\calculator.py)
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\main.py", line 42, in <module>
    from pages.calculator import calculator_page  
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


openai.lib._old_api.APIRemovedInV1: You tried to access openai.ChatCompletion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API. You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28` A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\ai_chatbox.py", line 46, in <module>
    ai_chatbox()
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\ai_chatbox.py", line 31, in ai_chatbox
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)



openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.
Traceback:
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\ai_chatbox.py", line 48, in <module>
    ai_chatbox()
File "D:\GITHUB Uploads\Project-from-songjong-course\Stock Market Website\pages\ai_chatbox.py", line 31, in ai_chatbox
    response = openai.Completion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
File "C:\Users\USER\anaconda3\Lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(


https://share.streamlit.io/errors/not_found

You do not have access to this app or it does not exist
You're currently signed in as ahantowsee.nasifa@gmail.com and with github.com/anahan07. Are you sure these accounts have access?

Sign out and sign in with a different account. If you are the app's developer, update the source control account associated with your account.

If you believe this is a bug, contact support.



Oh no.
Error running app. If you need help, try the Streamlit docs and forums.
